version: 2 

sources:
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ target.database.upper() | replace('_DEV', '') ~ '_DEV' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else target.database.upper() | replace('_DEV', '') }}
    tables:
      - name: blocks
      - name: transactions
      - name: tx_counts
  - name: crosschain_silver
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: silver
    tables:
      - name: labels_combined
      - name: number_sequence
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: hourly_prices_coin_gecko